src/io/fabric8/Utils.groovy
vars/clientsNode.groovy
vars/getNewVersion.groovy
vars/performCanaryRelease.groovy

fixes fabric8io/fabric8#6523
fixes fabric8io/fabric8#6527

general fixes for non java pipelines after recent upgrades

---

vars/mavenCanaryRelease.groovy

Will need to check for null but lets revert so that we fix users library asap
see fabric8io/fabric8#6593
This reverts commit ea368be769f97fe8a4d93f710200270c004dc54e.

Revert "allow to pass additional profiles to mvn build"

---

vars/genWebsiteDocs.groovy

A pipeline step that will generate website docs that will land in gh-pages

Added pipeline step 

---

ReadMe.md
vars/getDeploymentResources.groovy

add readiness and liveness checks for non java deployment resources

---

src/io/fabric8/Fabric8Commands.groovy
vars/pushPomPropertyChangePR.groovy

- pr also includes the removal of a catch {} to avoid not getting script approval messages

allow container name to be overwritten

---

vars/clientsTemplate.groovy
vars/mavenTemplate.groovy

These limits turned out to be the best compromise between resource consumption and speed for me

Add limits for maven build containers

---

ReadMe.md
pom.xml
src/io/fabric8/Utils.groovy
vars/mavenCanaryRelease.groovy

This causes issues on the fabric8 release infra
This reverts commit dfc56bf34d8859a5691eb1718cbbabf88bcfbae8.

Revert "Get the correct openshift build name rather than trying to guess it"

---

ReadMe.md
pom.xml
src/io/fabric8/Utils.groovy
vars/mavenCanaryRelease.groovy

This reverts commit 5e1dbf95918eab242745e47f282cf891cc715747.

Get the correct openshift build name rather than trying to guess it

---

src/io/fabric8/Utils.groovy
vars/mavenIntegrationTest.groovy

lets try use the new fabric8io API and if that fails lets use sensible defaults

lets fix up discovering the test namespace 

---

src/io/fabric8/Utils.groovy

see https://github.com/openshiftio/booster-common/issues/8

lets disable ITests until the boosters are fixed

---

vars/goMake.groovy
vars/goTemplate.groovy

These changes are for Kompose pr-building in Fabric8cd environment here http://jenkins.cd.k8s.fabric8.io/job/kubernetes-incubator/.
Here is the [Jenkinsfile](https://github.com/rupalibehera/kompose/blob/pr-pipeline/Jenkinsfile) for Kompose, once this PR is merged I will point to fabric8 pipeline library
Let me your suggestions on this ?
cc : @rawlingsj

Adding support for makeCommand and installPerequisites

---

vars/deployOpenShiftSnapshot.groovy

Reverts fabric8io/fabric8-pipeline-library#248
Openshift infra upgrade complete

Revert "disable ui snapshot deployments whilst OS infra upgrade is underway"

---

ReadMe.md

Minor patch to fix various typos in readme

Fix typos in ReadMe

---

vars/bayesianScanner.groovy

fix(#265): proper initialization of fabric8.Utils

---

.gitignore
src/io/fabric8/Fabric8Commands.groovy
src/io/fabric8/Utils.groovy
vars/mavenCanaryRelease.groovy
vars/mavenTemplate.groovy

so lets only override whether to use/not use docker if we have an explicit
configuration otherwise we default to whether S2I is supported

use the new optional configuration option

---

vars/approve.groovy

Timeout time defaults to 24 hours.

Adding timeout block for approval step

---

vars/pushNewDockerImageTagChangePR.groovy

We want to update the base docker image tag e.g `fabric8-openshift-nginx` in multiple projects whenever we include new stuff to the repository `fabric8-ui-openshift-nginx`.

Add function to update the docker base image tag in multiple projects

---

src/io/fabric8/Fabric8Commands.groovy
src/io/fabric8/Utils.groovy
vars/mavenCI.groovy
vars/mavenCanaryRelease.groovy
vars/mavenTemplate.groovy

- run maven builds in batch mode to avoid verbose logging
- refactor util method so it's easier to get users pipeline config
- don't mount m2 repo in build pods on plain kubernetes as we probably wont have RWX but will have nexus

improve releases on GKE

---

vars/apply.groovy

as the kubernetesApply() can now do that during the apply logic

lets remove the use of exposecontroller

---

vars/approve.groovy

see openshiftio/openshift.io#1042

move back to old way of approvals until we can test more outcomes with the new hubot plugin

---

vars/mavenTemplate.groovy

see https://github.com/fabric8io/kubernetes-model/pull/232

try removing the new xms and xms flags to see if that helps kubernetes-model build

---

vars/buildSnapshotFabric8UI.groovy

Since WIT pointed to prod-preview, pointed others

---

vars/mavenTemplate.groovy

Reverts fabric8io/fabric8-pipeline-library#349

Revert "Improve maven builder setup."

---

vars/mavenCanaryRelease.groovy

let's just use docker tag/push as it simplifies things

workaround dmp error Cannot temporarily tag because target image already exists.

---

vars/mavenTemplate.groovy

Enabling Java envVar

---

vars/chunkyTemplate.groovy
vars/deployTemplate.groovy
vars/mavenBuildSnapshot.groovy
vars/mavenTemplate.groovy
vars/releaseTemplate.groovy

Fixes https://github.com/openshiftio/openshift.io/issues/2368

Remove the PVs for maven caching

---

vars/mavenCanaryRelease.groovy

- fixed Integer parsing issue for FMP patching for #391 
- also, ensures that patching would not fail the pipeline build flow

update FMP patch

---

vars/chunkyTemplate.groovy
vars/clientsTemplate.groovy
vars/deployOpenShiftTemplate.groovy
vars/deployRemoteClusterTemplate.groovy
vars/dockerTemplate.groovy
vars/fabric8EETestTemplate.groovy
vars/fabric8UITemplate.groovy
vars/fabric8UITestTemplate.groovy
vars/goTemplate.groovy
vars/nodejsTemplate.groovy
vars/releaseTemplate.groovy
vars/s2iTemplate.groovy

Tested with https://github.com/edewit/fabric8-pipeline-library/tree/snapshot-test

chore(jenkins): updated jenkins slave to the latest version

---

vars/mavenCanaryRelease.groovy

chore: update version of the versions plugin

---

vars/spawn.groovy

fixes https://github.com/openshiftio/openshift.io/issues/4300

Adds command parameter in spawn api

---

vars/spawn.groovy

This will update slave images with
correct version and official images
Fixes https://github.com/openshiftio/openshift.io/issues/4161

Update slave images

---

src/io/fabric8/plugins/analytics.groovy
src/io/openshift/Events.groovy
src/io/openshift/Utils.groovy
vars/build.groovy
vars/deploy.groovy
vars/osio.groovy
vars/pod.groovy
vars/processTemplate.groovy

Make Utility function static and can be used
without creating an object of Utils class

 Improve Utility Class

---

vars/bayesianScanner.groovy

The previous command was not working as expected in cases which had multi maven modules.
Resolves: openshiftio/openshift.io#4361

Modified logic to create dependencies #4361

---

pom.xml
vars/bayesianScanner.groovy
vars/chunkyTemplate.groovy
vars/deployTemplate.groovy
vars/mavenBuildSnapshot.groovy
vars/mavenCI.groovy
vars/mavenCanaryRelease.groovy
vars/mavenIntegrationTest.groovy
vars/mavenTemplate.groovy

* mavenTemplate
* Change to use openshift/jenkins-slave-maven-centos7:v4.0
* Set mavenOpts -Duser.home=/home/jenkins
* Set secretVolume for mvnrepository to /home/jenkins

 Use upstream Maven image and set git config

---

vars/mavenTemplate.groovy

This will fix the issue of image not getting pulled
as for maven image 4.0 tag has been removed and
jnlp image has been moved to quay
Fixes https://github.com/openshiftio/openshift.io/issues/4755

Fix image pulling error
